AjaxPaging/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AjaxPaging.Helpers;
using AjaxPaging.Models;
namespace AjaxPaging.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {

        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
    }
}

AjaxPaging/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AjaxPaging.Helpers;
using AjaxPaging.Models;
namespace AjaxPaging.Controllers
{
    public class ProductController : Controller
    {
        public const int PageSize = 5;
        private List<Product> data = new List<Product>();
        public ProductController()
        {
            data.Add(new Product { ProductId = 1, ProductName = "ProductA", ProductCategory = "CatB" });
            data.Add(new Product { ProductId = 2, ProductName = "ProductA1", ProductCategory = "CatB1" });
            data.Add(new Product { ProductId = 3, ProductName = "ProductA2", ProductCategory = "CatB2" });
            data.Add(new Product { ProductId = 4, ProductName = "ProductC", ProductCategory = "CatC" });
            data.Add(new Product { ProductId = 5, ProductName = "ProductC1", ProductCategory = "CatC1" });
            data.Add(new Product { ProductId = 6, ProductName = "ProductC2", ProductCategory = "CatC2" });
            data.Add(new Product { ProductId = 7, ProductName = "ProductC2", ProductCategory = "CatC2" });
            data.Add(new Product { ProductId = 8, ProductName = "ProductD", ProductCategory = "CatE" });
            data.Add(new Product { ProductId = 9, ProductName = "ProductD1", ProductCategory = "CatE1" });
            data.Add(new Product { ProductId = 10, ProductName = "ProductD2", ProductCategory = "CatE2" });
            data.Add(new Product { ProductId = 11, ProductName = "ProductF1", ProductCategory = "CatG1" });
            data.Add(new Product { ProductId = 12, ProductName = "ProductF2", ProductCategory = "CatG2" });
            data.Add(new Product { ProductId = 13, ProductName = "ProductH1", ProductCategory = "CatI1" });
            data.Add(new Product { ProductId = 14, ProductName = "ProductH2", ProductCategory = "CatI2" });
            data.Add(new Product { ProductId = 15, ProductName = "ProductJ1", ProductCategory = "CatK1" });
            data.Add(new Product { ProductId = 16, ProductName = "ProductL1", ProductCategory = "CatM1" });
        }
        [HttpPost]
        public ActionResult ProductListPaged(PagedRequest request)
        {
            if (request.Page == null)
            {
                request.Page = 1;
            }
            var people = new PagedData<Product>();
            people.Request = request;
            people.Request.PageSize = PageSize;
            var query = data.AsQueryable();//Use EntityFramework 
            people.TotalEntries = query.Count();

            if (!string.IsNullOrWhiteSpace(request.KeySearch))
            {
                var keySearch =request.KeySearch.Trim();
                query = query.Where(x => x.ProductName.Contains(keySearch)||x.ProductCategory.Contains(keySearch));//demo how to search 
            }
            people.Data = query.OrderBy(p => p.ProductCategory).Skip(PageSize * (request.Page.Value - 1)).Take(PageSize).ToList();
            people.FilterdEntries = query.Count();
            people.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)people.FilterdEntries / PageSize));
            people.CurrentPage = request.Page.Value;
           

            return PartialView("_ProductListPaged", people);
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductList()
        {
            return PartialView();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AjaxPaging/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AjaxPaging/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h2>People</h2>
Demo a way to use server-side paging and some ajax method

@Html.Partial("~/Views/Person/PersonList.cshtml",null)

<div>
    See another example with Product page <a href="@Url.Action("Index","Product")"></a>
</div>
@Html.Partial("~/Views/Product/ProductList.cshtml", null )

AjaxPaging/Views/Home/PersonList.cshtml
@{ 
    var guid = Guid.NewGuid().ToString().Replace("-","");
}
<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <div style="margin-bottom:5px;">
        <input type="text" class="form-control" id="KeySearch_@guid" placeholder="Type to search" />
    </div>

    <div id="table-@guid" class="shadow-lg p-3 mb-5 bg-white rounded">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th class="">
                        Forename
                    </th>
                    <th>
                        Surname
                    </th>
                    <th>
                        Location
                    </th>
                </tr>
            </thead>
            <tbody id="table-body-@guid"></tbody>
        </table>
    </div>
    <div class="row container-fluid" >
        <div class="" id="table-found-@guid"></div>
        <div id="table-paging-@guid" class="col text-right">
        </div>
    </div>
</div>

<script type="text/javascript">
    var currentPage_@guid= 1;
    $(function () {
        //Load data for the first time
           $.ajax({
                url: '@Url.Action("PersonListPaged")',
                data: { "page": currentPage_@guid,guid:'@guid' },
               success: function (data) {
                   $("#table-body-@guid").html(data);
               }
        });
    });
    //set up event handler 
    function raisePageClick_@(guid)(pageNum) {
        currentPage_@guid = pageNum;
        $.ajax({
            url: '@Url.Action("PersonListPaged")',
            data: { "page": pageNum, guid: '@guid', keySearch: $('#KeySearch_@guid').val() },
            success: function (data) {
                $("#table-body-@guid").html(data);

            }
        });
    }

    $("#KeySearch_@guid").on("keyup", function () {
        setTimeout(function () {
                $.ajax({
                url: '@Url.Action("PersonListPaged")',
                  data: { "page": currentPage_@guid, guid: '@guid', keySearch: $('#KeySearch_@guid').val() },
                success: function (data) {
                    $("#table-body-@guid").html(data);

                }
            });
        }, 300);

         
    });

    window.addEventListener('Paging_Control_@(guid)', function (e) {
        var request = e.detail;
        currentPage_@guid = request.CurrentPage;
        $('#table-paging-@guid').html('');
        
        if (request.TotalEntries != undefined && request.TotalEntries > 0) {
            var keySearch = $("#KeySearch_@guid").val();
            if (keySearch != null) {
                keySearch = keySearch.trim();
            }
            if (keySearch != null && keySearch.length > 0) {
                //Build: Showing 1 to 10 of 68 entries (filtered from 105 total entries)
                var from = (request.CurrentPage - 1) * request.PageSize + 1;
                var to = from + request.PageSize - 1;
                if (to > request.FilterdEntries) {
                    to = request.FilterdEntries;
                };
                $('#table-found-@guid').html('Showing ' + from.toString() + ' to ' + to.toString() + ' of ' + request.FilterdEntries + ' entries (filtered from ' + request.TotalEntries + ' total entries)');
            }
            else {
                var from = (request.CurrentPage - 1) * request.PageSize + 1;
                var to = from + request.PageSize - 1;
                if (to > request.TotalEntries) {
                    to = request.TotalEntries;
                };
                $('#table-found-@guid').html('Showing ' + from.toString() + ' to ' + to.toString() + ' of ' + request.TotalEntries + ' entries ');
            }

        }
        else {
            $('#table-found-@guid').html('No data found ');
        }
        if (request.NumberOfPages != undefined && request.NumberOfPages != null)
        {
           

            var content = '<nav aria-label="Page navigation example">';
          
            content += '<ul class="pagination justify-content-end">';

            for (var i = 1; i <= request.NumberOfPages; i++) {
                if (i == request.CurrentPage) {
                    content += '<li class="page-item active">';
                    content += '<a class="page-link" href="#">' + i.toString() + ' <span class="sr-only">(current)</span></a>';
                    content += '</li>';
                }
                else {
                    content += '<li class="page-item"><a class="page-link" href="#" onclick="raisePageClick_@(guid)(' + i.toString() + ')">' + i.toString() + '</a ></li >';
                }
               
            }
            content += '</ul >';
            content += '</nav >';
            $('#table-paging-@guid').html(content);
        }

    });
    
</script>

AjaxPaging/Views/Home/PersonListPaged.cshtml
@model AjaxPaging.Helpers.PagedData<AjaxPaging.Models.Person>
@{
}


        @foreach (var person in Model.Data)
        {
            <tr>
                <td>
                    @person.Forename
                </td>
                <td>
                    @person.Surname
                </td>
                <td>
                    @person.Country
                </td>
            </tr>
        }

<script>
   
      $(function () {
        //raise paging data
          window.dispatchEvent(new CustomEvent('Paging_Control_@Model.Request.Guid', { detail: { CurrentPage: @Model.CurrentPage, NumberOfPages: @Model.NumberOfPages, TotalEntries:@Model.TotalEntries, PageSize:@Model.Request.PageSize, FilterdEntries:@Model.FilterdEntries } }));
    
    
    });
  
</script>